### ISSUE TITLE
Sounds very interesting!

### ISSUE THREAD

**Issue by Chris-May** [at-import/SUCKS#2]
How can the community help out?

**Comment by dilrajahdan** [comment]
+1 - how can we help?

Im already using this style of class naming in my current projects. So far so good. It looks nicer then BEM.

**Comment by Snugug** [comment]
I think it's fairly safe to say this project is dead, we haven't ouched it since our initial interest. My thoughts on this topic are currently encompassed in [North](http://pointnorth.io/#styling)
